# Generated by Django 4.2.10 on 2024-02-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='price',
        ),
        migrations.RemoveField(
            model_name='new',
            name='quantity',
        ),
    ]
